name: Lint

on: [pull_request]

jobs:
  lintMatchingVersions:
    name: "Ensure matching manifest versions"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "compare version"
      run: |
        packageVersion=$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' package.json)
        manifestVersion=$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' common/manifest.json)
        chromeManifestVersion=$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' chrome/manifest.json)
        [[ $packageVersion = $manifestVersion ]]
        [[ $chromeManifestVersion = $manifestVersion ]]

  lintExtension:
    name: "Lint Firefox extension"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cmd: lint
          source: common
          channel: listed

